# -*- coding: utf-8 -*-
"""Копия 2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckpt4Wdw_gzuF8bpy46rIZ-2QijoOxzY
"""

from scipy import stats
import numpy as np

print('Задание 1.')

# 1. Найти скалярное произведение векторов x,y ∈ R:
# а) x=(0,−3,6), y=(−4,7,9);
# б) x=(7,−4,0,1), y=(−3,1,11,2).

x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])

print('Скалярное произведение х и у:', np.dot(x, y))

x1 = np.array([7, -4, 0, 1])
y1 = np.array([-3, 1, 11, 2])

print('Скалярное произведение х1 и у1:', np.dot(x1, y1))

from numpy.linalg import norm

print('Задание 2.')

# Найти нормы векторов (4,2,4) и (12,3,4) и угол между ними.

a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

print('Манхеттенская норма вектора а:', norm(a, ord=1))
print('Евклидова норма вектора а', norm(a, ord=2))
print('Манхеттенская норма вектора b', norm(b, ord=1))
print('Евклидова норма вектора b', norm(b, ord=2))
print('Угол между векторами а и b: cos', np.dot(a, b) / (norm(a) * norm(b)))